-- Bộ từ vựng demo DB-CONTENT-001 được tự biên soạn ngày 2026-09-28.
-- Nguồn gốc và cách rà soát: docs/database/DB-CONTENT-001-demo-vocabulary-provenance.md.
-- ID xác định theo mức, từ và từ loại; rerun không ghi đè nội dung đã được biên tập.
WITH seed(code, word, part_of_speech, meaning_vi) AS (
    VALUES
    ('A1', 'apple', 'noun', 'quả táo'),
    ('A1', 'book', 'noun', 'quyển sách'),
    ('A1', 'bread', 'noun', 'bánh mì'),
    ('A1', 'chair', 'noun', 'cái ghế'),
    ('A1', 'child', 'noun', 'đứa trẻ'),
    ('A1', 'city', 'noun', 'thành phố'),
    ('A1', 'clock', 'noun', 'đồng hồ'),
    ('A1', 'door', 'noun', 'cánh cửa'),
    ('A1', 'family', 'noun', 'gia đình'),
    ('A1', 'friend', 'noun', 'người bạn'),
    ('A1', 'garden', 'noun', 'khu vườn'),
    ('A1', 'house', 'noun', 'ngôi nhà'),
    ('A1', 'kitchen', 'noun', 'nhà bếp'),
    ('A1', 'letter', 'noun', 'lá thư'),
    ('A1', 'market', 'noun', 'chợ'),
    ('A1', 'mother', 'noun', 'mẹ'),
    ('A1', 'picture', 'noun', 'bức tranh'),
    ('A1', 'school', 'noun', 'trường học'),
    ('A1', 'shirt', 'noun', 'áo sơ mi'),
    ('A1', 'street', 'noun', 'đường phố'),
    ('A1', 'table', 'noun', 'cái bàn'),
    ('A1', 'teacher', 'noun', 'giáo viên'),
    ('A1', 'train', 'noun', 'tàu hỏa'),
    ('A1', 'water', 'noun', 'nước'),
    ('A1', 'window', 'noun', 'cửa sổ'),
    ('A1', 'write', 'verb', 'viết'),
    ('A1', 'read', 'verb', 'đọc'),
    ('A1', 'sleep', 'verb', 'ngủ'),
    ('A1', 'smile', 'verb', 'mỉm cười'),
    ('A1', 'walk', 'verb', 'đi bộ'),
    ('A2', 'appointment', 'noun', 'cuộc hẹn'),
    ('A2', 'baggage', 'noun', 'hành lý'),
    ('A2', 'bridge', 'noun', 'cây cầu'),
    ('A2', 'calendar', 'noun', 'lịch'),
    ('A2', 'customer', 'noun', 'khách hàng'),
    ('A2', 'destination', 'noun', 'điểm đến'),
    ('A2', 'discount', 'noun', 'khoản giảm giá'),
    ('A2', 'entrance', 'noun', 'lối vào'),
    ('A2', 'factory', 'noun', 'nhà máy'),
    ('A2', 'festival', 'noun', 'lễ hội'),
    ('A2', 'flight', 'noun', 'chuyến bay'),
    ('A2', 'hobby', 'noun', 'sở thích'),
    ('A2', 'invitation', 'noun', 'lời mời'),
    ('A2', 'journey', 'noun', 'hành trình'),
    ('A2', 'library', 'noun', 'thư viện'),
    ('A2', 'medicine', 'noun', 'thuốc'),
    ('A2', 'museum', 'noun', 'bảo tàng'),
    ('A2', 'neighbor', 'noun', 'người hàng xóm'),
    ('A2', 'passport', 'noun', 'hộ chiếu'),
    ('A2', 'platform', 'noun', 'sân ga'),
    ('A2', 'receipt', 'noun', 'biên lai'),
    ('A2', 'reservation', 'noun', 'việc đặt chỗ'),
    ('A2', 'restaurant', 'noun', 'nhà hàng'),
    ('A2', 'schedule', 'noun', 'lịch trình'),
    ('A2', 'suitcase', 'noun', 'va li'),
    ('A2', 'temperature', 'noun', 'nhiệt độ'),
    ('A2', 'ticket', 'noun', 'vé'),
    ('A2', 'traffic', 'noun', 'giao thông'),
    ('A2', 'vacation', 'noun', 'kỳ nghỉ'),
    ('A2', 'wallet', 'noun', 'ví tiền'),
    ('B1', 'achievement', 'noun', 'thành tựu'),
    ('B1', 'advantage', 'noun', 'lợi thế'),
    ('B1', 'attitude', 'noun', 'thái độ'),
    ('B1', 'behavior', 'noun', 'hành vi'),
    ('B1', 'challenge', 'noun', 'thử thách'),
    ('B1', 'community', 'noun', 'cộng đồng'),
    ('B1', 'confidence', 'noun', 'sự tự tin'),
    ('B1', 'consequence', 'noun', 'hậu quả'),
    ('B1', 'culture', 'noun', 'văn hóa'),
    ('B1', 'decision', 'noun', 'quyết định'),
    ('B1', 'delivery', 'noun', 'việc giao hàng'),
    ('B1', 'environment', 'noun', 'môi trường'),
    ('B1', 'evidence', 'noun', 'bằng chứng'),
    ('B1', 'experience', 'noun', 'kinh nghiệm'),
    ('B1', 'improvement', 'noun', 'sự cải thiện'),
    ('B1', 'influence', 'noun', 'sự ảnh hưởng'),
    ('B1', 'opportunity', 'noun', 'cơ hội'),
    ('B1', 'permission', 'noun', 'sự cho phép'),
    ('B1', 'population', 'noun', 'dân số'),
    ('B1', 'priority', 'noun', 'việc ưu tiên'),
    ('B1', 'relationship', 'noun', 'mối quan hệ'),
    ('B1', 'responsibility', 'noun', 'trách nhiệm'),
    ('B1', 'solution', 'noun', 'giải pháp'),
    ('B1', 'tradition', 'noun', 'truyền thống'),
    ('B1', 'volunteer', 'noun', 'tình nguyện viên'),
    ('B1', 'warn', 'verb', 'cảnh báo'),
    ('B1', 'compare', 'verb', 'so sánh'),
    ('B1', 'describe', 'verb', 'mô tả'),
    ('B1', 'persuade', 'verb', 'thuyết phục'),
    ('B1', 'recommend', 'verb', 'đề xuất'),
    ('B2', 'adaptation', 'noun', 'sự thích nghi'),
    ('B2', 'assumption', 'noun', 'giả định'),
    ('B2', 'awareness', 'noun', 'nhận thức'),
    ('B2', 'bias', 'noun', 'thiên kiến'),
    ('B2', 'circumstance', 'noun', 'hoàn cảnh'),
    ('B2', 'commitment', 'noun', 'cam kết'),
    ('B2', 'compromise', 'noun', 'sự thỏa hiệp'),
    ('B2', 'controversy', 'noun', 'tranh cãi'),
    ('B2', 'criterion', 'noun', 'tiêu chí'),
    ('B2', 'decline', 'noun', 'sự suy giảm'),
    ('B2', 'diversity', 'noun', 'sự đa dạng'),
    ('B2', 'efficiency', 'noun', 'hiệu suất'),
    ('B2', 'emphasis', 'noun', 'sự nhấn mạnh'),
    ('B2', 'framework', 'noun', 'khuôn khổ'),
    ('B2', 'insight', 'noun', 'hiểu biết sâu sắc'),
    ('B2', 'interpretation', 'noun', 'cách diễn giải'),
    ('B2', 'investment', 'noun', 'khoản đầu tư'),
    ('B2', 'negotiation', 'noun', 'cuộc đàm phán'),
    ('B2', 'obstacle', 'noun', 'trở ngại'),
    ('B2', 'perspective', 'noun', 'góc nhìn'),
    ('B2', 'phenomenon', 'noun', 'hiện tượng'),
    ('B2', 'proposal', 'noun', 'đề xuất bằng văn bản'),
    ('B2', 'regulation', 'noun', 'quy định'),
    ('B2', 'reliability', 'noun', 'độ tin cậy'),
    ('B2', 'strategy', 'noun', 'chiến lược'),
    ('B2', 'sustainability', 'noun', 'tính bền vững'),
    ('B2', 'tendency', 'noun', 'xu hướng'),
    ('B2', 'transition', 'noun', 'sự chuyển đổi'),
    ('B2', 'uncertainty', 'noun', 'sự bất định'),
    ('B2', 'welfare', 'noun', 'phúc lợi'),
    ('C1', 'ambiguity', 'noun', 'tính mơ hồ'),
    ('C1', 'coherence', 'noun', 'tính mạch lạc'),
    ('C1', 'concession', 'noun', 'sự nhượng bộ'),
    ('C1', 'consensus', 'noun', 'sự đồng thuận'),
    ('C1', 'constraint', 'noun', 'sự ràng buộc'),
    ('C1', 'credibility', 'noun', 'tính đáng tin'),
    ('C1', 'discrepancy', 'noun', 'sự sai lệch'),
    ('C1', 'discretion', 'noun', 'quyền tự quyết'),
    ('C1', 'dissent', 'noun', 'ý kiến bất đồng'),
    ('C1', 'elaboration', 'noun', 'sự diễn giải chi tiết'),
    ('C1', 'expenditure', 'noun', 'khoản chi tiêu'),
    ('C1', 'feasibility', 'noun', 'tính khả thi'),
    ('C1', 'fluctuation', 'noun', 'sự dao động'),
    ('C1', 'implication', 'noun', 'hàm ý'),
    ('C1', 'incentive', 'noun', 'động lực khuyến khích'),
    ('C1', 'inequality', 'noun', 'sự bất bình đẳng'),
    ('C1', 'integrity', 'noun', 'tính chính trực'),
    ('C1', 'intervention', 'noun', 'sự can thiệp'),
    ('C1', 'legitimacy', 'noun', 'tính chính danh'),
    ('C1', 'liability', 'noun', 'trách nhiệm pháp lý'),
    ('C1', 'magnitude', 'noun', 'độ lớn'),
    ('C1', 'nuance', 'noun', 'sắc thái tinh tế'),
    ('C1', 'precedent', 'noun', 'tiền lệ'),
    ('C1', 'resilience', 'noun', 'khả năng phục hồi'),
    ('C1', 'scrutiny', 'noun', 'sự xem xét kỹ lưỡng'),
    ('C1', 'synthesis', 'noun', 'sự tổng hợp'),
    ('C1', 'transparency', 'noun', 'tính minh bạch'),
    ('C1', 'validity', 'noun', 'tính hợp lệ'),
    ('C1', 'viability', 'noun', 'khả năng tồn tại'),
    ('C1', 'vulnerability', 'noun', 'tính dễ bị tổn thương'),
    ('C2', 'aberration', 'noun', 'sự lệch chuẩn bất thường'),
    ('C2', 'acquiescence', 'noun', 'sự chấp thuận miễn cưỡng'),
    ('C2', 'anomaly', 'noun', 'điều dị thường'),
    ('C2', 'antithesis', 'noun', 'điều đối lập hoàn toàn'),
    ('C2', 'apathy', 'noun', 'sự thờ ơ'),
    ('C2', 'arbitrariness', 'noun', 'tính tùy tiện'),
    ('C2', 'brevity', 'noun', 'tính ngắn gọn'),
    ('C2', 'circumspection', 'noun', 'sự thận trọng kín kẽ'),
    ('C2', 'conundrum', 'noun', 'vấn đề hóc búa'),
    ('C2', 'corroboration', 'noun', 'sự xác nhận bằng chứng cứ'),
    ('C2', 'deference', 'noun', 'sự kính trọng nhường nhịn'),
    ('C2', 'dichotomy', 'noun', 'sự phân đôi đối lập'),
    ('C2', 'equanimity', 'noun', 'sự bình thản'),
    ('C2', 'exigency', 'noun', 'nhu cầu cấp bách'),
    ('C2', 'fallacy', 'noun', 'lập luận sai lầm'),
    ('C2', 'fortitude', 'noun', 'nghị lực trước nghịch cảnh'),
    ('C2', 'idiosyncrasy', 'noun', 'nét tính cách riêng biệt'),
    ('C2', 'impasse', 'noun', 'thế bế tắc'),
    ('C2', 'incongruity', 'noun', 'sự không tương hợp'),
    ('C2', 'intransigence', 'noun', 'sự cố chấp không nhượng bộ'),
    ('C2', 'mendacity', 'noun', 'tính dối trá'),
    ('C2', 'obfuscation', 'noun', 'sự cố ý làm khó hiểu'),
    ('C2', 'ostentation', 'noun', 'sự phô trương'),
    ('C2', 'perfunctory', 'adjective', 'qua loa chiếu lệ'),
    ('C2', 'quandary', 'noun', 'tình thế khó xử'),
    ('C2', 'recalcitrant', 'adjective', 'ngoan cố chống đối'),
    ('C2', 'subterfuge', 'noun', 'mánh khóe che giấu'),
    ('C2', 'tenacity', 'noun', 'tính kiên trì'),
    ('C2', 'ubiquity', 'noun', 'tính hiện diện khắp nơi'),
    ('C2', 'vicissitude', 'noun', 'sự đổi thay thăng trầm')
)
INSERT INTO vocabulary (
    id, word, meaning_vi, part_of_speech, cefr_level_id,
    source, is_active, created_at, updated_at
)
SELECT md5('DB-CONTENT-001:' || seed.code || ':' || seed.word || ':' || seed.part_of_speech)::uuid,
       seed.word, seed.meaning_vi, seed.part_of_speech, levels.id,
       'MANUAL', TRUE, now(), now()
FROM seed
JOIN cefr_levels AS levels ON levels.code = seed.code
ON CONFLICT (word, part_of_speech, cefr_level_id) DO NOTHING;
